# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "colorize", "~> 0.8.1"

gem "tty-prompt", "~> 0.19.0"

gem "tty-table", "~> 0.11.0"

gem "tty-font", "~> 0.4.0"

gem "terminal-table", "~> 1.8"
